-- Schema fiel da produção (JPR) gerado por introspecção. Schema-only, sem dados.
-- Alvo: schema public.

-- ========== EXTENSIONS ==========
create extension if not exists "pg_stat_statements" with schema "extensions";
create extension if not exists "pgcrypto" with schema "extensions";
create extension if not exists "supabase_vault" with schema "vault";
create extension if not exists "uuid-ossp" with schema "extensions";
create extension if not exists "vector" with schema "public";

-- ========== TABLES ==========
create table if not exists public."documents" (
  "id" bigint generated always as identity not null,
  "content" text,
  "fts" tsvector generated always as (to_tsvector('english'::regconfig, content)) stored,
  "embedding" vector(1536),
  "metadata" jsonb
);

create table if not exists public."leads" (
  "id" bigint generated always as identity not null,
  "nome" text not null,
  "modelo_desejado" text not null,
  "armazenamento_desejado" text,
  "modelo_entrada" text,
  "armazenamento_entrada" text,
  "interesse" text default 'comprar_seminovo'::text,
  "tipo" text default 'comprador'::text not null,
  "orcamento" numeric(10,2),
  "urgencia" text default 'longo_prazo'::text,
  "temperatura" text default 'frio'::text,
  "origem" text,
  "responsavel" text,
  "kommo_lead_id" text,
  "status" text default 'ativo'::text,
  "created_at" timestamp with time zone default now(),
  "updated_at" timestamp with time zone default now()
);

create table if not exists public."presets" (
  "id" uuid default gen_random_uuid() not null,
  "name" text not null,
  "config" jsonb not null,
  "created_at" timestamp with time zone default now()
);

create table if not exists public."produtos" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone default now() not null,
  "novo_seminovo" text,
  "produto" text,
  "preco" text,
  "cores" text,
  "revendedor" text,
  "armazenamento" text,
  "sku" text,
  "atualized_at" timestamp without time zone,
  "fora_do_club" text,
  "parcelado12" text,
  "economia" text,
  "total" text,
  "prazo" text,
  "status_estoque" text,
  "observacoes" text,
  "custo" text
);

create table if not exists public."produtos_backup" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone default now() not null,
  "novo_seminovo" text,
  "produto" text,
  "preco" text,
  "cores" text,
  "revendedor" text,
  "armazenamento" text,
  "sku" text,
  "atualized_at" timestamp without time zone
);

create table if not exists public."rate_configs" (
  "id" text default 'default'::text not null,
  "config" jsonb not null,
  "updated_at" timestamp with time zone default now() not null
);

-- ========== CONSTRAINTS ==========
alter table public."documents" add constraint "documents_pkey" PRIMARY KEY (id);
alter table public."leads" add constraint "leads_pkey" PRIMARY KEY (id);
alter table public."leads" add constraint "leads_kommo_lead_id_key" UNIQUE (kommo_lead_id);
alter table public."leads" add constraint "unique_kommo_lead_id" UNIQUE (kommo_lead_id);
alter table public."presets" add constraint "presets_pkey" PRIMARY KEY (id);
alter table public."produtos" add constraint "produtos_rev_pkey" PRIMARY KEY (id);
alter table public."produtos" add constraint "produtos_sku_key" UNIQUE (sku);
alter table public."produtos_backup" add constraint "produtos_backup_pkey" PRIMARY KEY (id);
alter table public."produtos_backup" add constraint "produtos_backup_sku_key" UNIQUE (sku);
alter table public."rate_configs" add constraint "rate_configs_pkey" PRIMARY KEY (id);

-- ========== INDEXES ==========
CREATE INDEX documents_fts_idx ON public.documents USING gin (fts);
CREATE INDEX documents_embedding_idx ON public.documents USING hnsw (embedding vector_ip_ops);
CREATE INDEX idx_leads_modelo_desejado ON public.leads USING btree (modelo_desejado);
CREATE INDEX idx_leads_modelo_entrada ON public.leads USING btree (modelo_entrada);
CREATE INDEX idx_leads_tipo ON public.leads USING btree (tipo);
CREATE INDEX idx_leads_status ON public.leads USING btree (status);

-- ========== FUNCTIONS ==========
CREATE OR REPLACE FUNCTION public.hybrid_search(query_text text, query_embedding vector, match_count integer, full_text_weight double precision DEFAULT 1, semantic_weight double precision DEFAULT 1, rrf_k integer DEFAULT 50)
 RETURNS TABLE(id bigint, content text, score double precision, rank integer)
 LANGUAGE sql
AS $function$
with full_text as (
  select
    id,
    row_number() over(order by ts_rank_cd(fts, websearch_to_tsquery(query_text)) desc) as rank_ix
  from
    documents
  where
    fts @@ websearch_to_tsquery(query_text)
  limit least(match_count, 30) * 2
),
semantic as (
  select
    id,
    row_number() over (order by embedding <#> query_embedding) as rank_ix
  from
    documents
  limit least(match_count, 30) * 2
),
merged as (
  select
    coalesce(ft.id, sem.id) as id,
    ft.rank_ix as ft_rank,
    sem.rank_ix as sem_rank
  from
    full_text ft
    full outer join semantic sem on ft.id = sem.id
),
scored as (
  select
    m.id,
    cd.content,
    coalesce(1.0 / (rrf_k + m.ft_rank), 0.0) * full_text_weight +
    coalesce(1.0 / (rrf_k + m.sem_rank), 0.0) * semantic_weight as score
  from
    merged m
    join documents cd on cd.id = m.id
)
select
  id,
  content,
  score,
  row_number() over (order by score desc) as rank
from
  scored
order by
  score desc
limit
  least(match_count, 30)
$function$
;

-- ========== RLS ==========
alter table public."rate_configs" enable row level security;
create policy "rate_configs_insert" on public."rate_configs" as PERMISSIVE for INSERT to public with check (true);
create policy "rate_configs_select" on public."rate_configs" as PERMISSIVE for SELECT to public using (true);
create policy "rate_configs_update" on public."rate_configs" as PERMISSIVE for UPDATE to public using (true) with check (true);

-- ========== GRANTS ==========
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."documents" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."documents" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."documents" to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."leads" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."leads" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."leads" to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."presets" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."presets" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."presets" to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."produtos" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."produtos" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."produtos" to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."produtos_backup" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."produtos_backup" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."produtos_backup" to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."rate_configs" to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."rate_configs" to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public."rate_configs" to service_role;
